[tool.black]
line-length = 88
skip-string-normalization = false
skip-magic-trailing-comma = false

[tool.ruff]
line-length = 88
indent-width = 1
select = ["E", "F", "W", "I"]
ignore = []
exclude = [".git", "__pycache__", ".venv", "venv", "env", "build", "dist"]

[tool.ruff.format]
indent-style = "tab"
